name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-root
        poetry install --no-interaction
    
    - name: Show installed packages
      run: poetry show
    
    - name: Run tests
      run: |
        poetry run pytest tests/ --cov=clade_mcp_agent --cov-report=xml
    
    - name: Run linting
      run: |
        poetry run flake8 clade_mcp_agent/ tests/ 